# install_pre_commit.ps1 — Windows PowerShell 装 git pre-commit hook
# 用法:在私库根跑 powershell -File serenity-bottleneck-hunter\scripts\install_pre_commit.ps1
#
# 装两个仓库的 hook(私库 + 公库 serenity-bottleneck-hunter)

$REPOS = @(
    "C:\Users\yijie12.liu\Desktop\AI辅助工作\Serenity",
    "C:\Users\yijie12.liu\Desktop\AI辅助工作\serenity-bottleneck-hunter"
)

foreach ($repo in $REPOS) {
    $hookDir = Join-Path $repo ".git\hooks"
    if (-not (Test-Path $hookDir)) {
        Write-Host "Skip: $repo - no .git/hooks dir"
        continue
    }
    $hookPath = Join-Path $hookDir "pre-commit"

    # 私库走 serenity-bottleneck-hunter\scripts\verify_tickers.py
    # 公库走 scripts\verify_tickers.py
    if ($repo -like "*Serenity") {
        $verifyPath = "serenity-bottleneck-hunter/scripts/verify_tickers.py"
    } else {
        $verifyPath = "scripts/verify_tickers.py"
    }

    # 用 sh-style hook (Git Bash 解析) + 调用 python
    # 注意:EODHD_API_KEY 必须在 user shell env 里自己 export,不硬编码在 hook
    # (避免 key 泄露 — 即使 .git/hooks/ 不被 git tracked,install 脚本本身被 tracked,key 不能进源码)
    $hookContent = @"
#!/bin/sh
# Auto-generated by install_pre_commit.ps1 on $(Get-Date -Format 'yyyy-MM-dd')
# 拦截 ticker / 公司名 mismatch — L1+L2+L3 防御
# REQUIRES: EODHD_API_KEY env var (用户自行 export 在 ~/.bashrc 或 system env)
if [ -z "`$EODHD_API_KEY" ]; then
    echo "[pre-commit] WARN: EODHD_API_KEY not set — verify will use cached ticker_truth.csv only"
fi
python "$verifyPath" --staged
exit `$?
"@
    Set-Content -Path $hookPath -Value $hookContent -Encoding UTF8
    Write-Host "Installed: $hookPath -> $verifyPath"
}

Write-Host ""
Write-Host "完成。下次 git commit 前会自动 scan staged 文件 ticker mismatch。"
Write-Host "bypass(仅紧急):git commit --no-verify"
